[workspace]
resolver = "2"
members = [
    "crates/fj",
    "crates/fj-app",
    "crates/fj-export",
    "crates/fj-host",
    "crates/fj-interop",
    "crates/fj-kernel",
    "crates/fj-math",
    "crates/fj-operations",
    "crates/fj-viewer",

    "models/cuboid",
    "models/group",
    "models/spacer",
    "models/star",
    "models/union",

    "tools/export-validator",
    "tools/release-operator",
]
default-members = [
    "crates/fj-app",
    "crates/fj-export",
    "crates/fj-host",
    "crates/fj-interop",
    "crates/fj-kernel",
    "crates/fj-math",
    "crates/fj-operations",
    "crates/fj-viewer",
]
